def dibujarSoga(intento):
    if intento == -1:
        print('  ____  ')
        print('  |   | ')
        print('  |     ')
        print('  |  \o/')
        print('  |   | ')
        print(' / \ / \\')
    if intento == 0:
        print('  ____  ')
        print('  |   | ')
        print('  |     ')
        print('  |     ')
        print('  |     ')
        print(' / \    ')
    if intento == 1:
        print('  ____  ')
        print('  |   | ')
        print('  |   o ')
        print('  |     ')
        print('  |     ')
        print(' / \    ')
    if intento == 2:
        print('  ____  ')
        print('  |   | ')
        print('  |   o ')
        print('  |   | ')
        print('  |     ')
        print(' / \    ')
    if intento == 3:
        print('  ____  ')
        print('  |   | ')
        print('  |   o ')
        print('  |  -| ')
        print('  |     ')
        print(' / \    ')
    if intento == 4:
        print('  ____  ')
        print('  |   | ')
        print('  |   o ')
        print('  |  -|-')
        print('  |     ')
        print(' / \    ')
    if intento == 5:
        print('  ____  ')
        print('  |   | ')
        print('  |   o ')
        print('  |  -|-')
        print('  |  /  ')
        print(' / \    ')
    if intento >= 6:
        print('  ____  ')
        print('  |   | ')
        print('  |   o ')
        print('  |  -|-')
        print('  |  / \\')
        print(' / \    ')
        print('        ')
        print('Has perdido.')
        print('        ')
